version: "3.5"

services:
  client:
    container_name: mytexter_client
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./.env
    volumes:
      - .:/client
      - /client/node_modules
    ports:
      - 3000:3000
    command: npm run start
