version: "3.0"

services:
  #MySQL
  db:
    image: mysql
    container_name: mysql_for_myTexter
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
