version: "3"

services:
  client:
    container_name: mytexter_client
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/client
      - /client/node_modules
    ports:
      - 3000:3000
    command: npm run start
